# Generated by Django 5.0.7 on 2024-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_rename_receipe_receipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipes',
            name='r_image',
            field=models.ImageField(upload_to='receipes'),
        ),
    ]
