# Generated by Django 5.0.7 on 2024-07-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_receipe_delete_receipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='receipe',
        ),
    ]
