# Generated by Django 5.0.7 on 2024-07-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vege', '0005_delete_receipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_des', models.TextField()),
                ('r_image', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
