# Generated by Django 5.0.7 on 2024-07-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='r_des',
            new_name='receipi_description',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='r_image',
            new_name='receipi_image',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='r_name',
            new_name='receipi_name',
        ),
    ]
