# Generated by Django 5.0.7 on 2024-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_rename_r_des_receipes_receipi_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='receipi_description',
            new_name='rdesc',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='receipi_image',
            new_name='rimg',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='receipi_name',
            new_name='rname',
        ),
    ]
