# Generated by Django 5.0.7 on 2024-07-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_rename_receipi_description_receipes_rdesc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='rdesc',
            new_name='receipi_description',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='rimg',
            new_name='receipi_image',
        ),
        migrations.RenameField(
            model_name='receipes',
            old_name='rname',
            new_name='receipi_name',
        ),
    ]
