# Generated by Django 5.0.7 on 2024-07-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='StudentID',
            new_name='student_id',
        ),
    ]
