# Generated by Django 5.0.7 on 2024-07-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0015_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(max_length=100),
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
