# Generated by Django 5.0.7 on 2024-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0016_alter_student_student_id_delete_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
