# Generated by Django 5.0.7 on 2024-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0019_alter_studentid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
