# Generated by Django 5.0.7 on 2024-07-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0020_alter_studentid_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
    ]
