# Generated by Django 5.0.7 on 2024-07-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0022_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
