# Generated by Django 5.0.7 on 2024-07-25 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0024_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 7, 25, 3, 43, 14, 878511, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
