# Generated by Django 5.0.7 on 2024-07-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0025_receipes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipes',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
